version: '3.8'

services:
  mariadb:
    container_name: mariadb_gestassoc
    image: mariadb:10.5.23-focal
    ports:
      - "3306:3306"
    env_file:
      - .env.test
    environment:
      TZ: Europe/Paris
    volumes:
      - ./backup:/backup

  phpmyadmin:
    container_name: phpmyadmin_gestassoc
    image: phpmyadmin:5.2.1-apache
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    env_file:
      - .env.test

volumes:
  mariadb_data:
    driver: local
