version: '3.8'

services:
  mariadb:
    container_name: mariadb-gestassoc
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    env_file:
      - .env.test

  phpmyadmin:
    container_name: phpmyadmin-gestassoc
    image: phpmyadmin:5.2.1-apache
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    env_file:
      - .env.test

volumes:
  mariadb_data:
    driver: local
