version: '3'
services:
    mongodb:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: mongodb
      ports:
        - "27017:27017"
      volumes:
        - ./data:/data/db
        - ./init.json:/init.json
      restart: always
