openapi: 3.1.0
info:
  title: Event API
  version: 1.0.0
paths:
  /events:
    get:
      summary: Liste tous les événements
      responses:
        '200':
          description: Une liste d'événements
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventList'
    post:
      summary: Crée un nouvel événement
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
      responses:
        '201':
          description: Un nouvel événement créé

  /events/{eventId}:
    get:
      summary: Récupère un événement par son ID
      parameters:
      - name: eventId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Un événement détaillé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
    put:
      summary: Met à jour un événement
      parameters:
      - name: eventId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
      responses:
        '200':
          description: Événement mis à jour
    delete:
      summary: Supprime un événement
      parameters:
      - name: eventId
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: Événement supprimé

components:
  schemas:
    Event:
      type: object
      required:
        - id
        - title
      properties:
        id:
          type: int
        title:
          type: string
        description:
          type: string
        location:
          $ref: '#/components/schemas/Location'
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
    EventList:
      type: array
      items:
        $ref: '#/components/schemas/Event'
    Location:
      type: object
      properties:
        name:
          type: string
        address:
          type: string
        latitude:
          type: number
        longitude:
          type: number